### ISSUE TITLE
After /login, VRE should redirect to referer rather than to default /virtualfolder/

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/VRE#10]
When going to /virtualfolder/filepickercomponent.html - 403 is redirected to /login and after user logs in, it is not redirected back to filepickercomponent.html but only to the default /virtualfolder/ (vf settings not the file picker component).

The desired behavior is that whatever component or page within /virtualfolder/[component.html] initiates to redirect to /login - it should be returned back by VRE e.g. using HTTP referer.

**Comment by Benzene** [comment]
If you redirect to /login?next=/virtualfolder/[component.html], the user will now be redirected back to /virtualfolder/[component.html] after the user logs in.

I tried to set it automatically from the referer, but there are too many strange edges cases and problems because going to the SSO and back again loses the referer information.

I'll make a pull request on the virtualfolder side to use this.
