### ISSUE TITLE
Cannot login VRE in single VM scenario

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/VRE#5]
Cannot login VRE in single VM scenario.  I'm not sure if it would be possible as single VM instance has obviously no fixed IP nor FQDN. 

The following is thrown
AttributeError at /saml2/login/

'Settings' object has no attribute 'SAML_CONFIG'

Request Method:     GET
Request URL:    http://127.0.0.1:8004/saml2/login/
Django Version:     1.8.14
Exception Type:     AttributeError
Exception Value:    

'Settings' object has no attribute 'SAML_CONFIG'

Exception Location:     /home/vagrant/VRE-master/.pyvenv/lib/python2.7/site-packages/django/conf/**init**.py in **getattr**, line 49
Python Executable:  /home/vagrant/VRE-master/.pyvenv/bin/python
Python Version:     2.7.5
Python Path:    

['/home/vagrant/VRE-master',
 '/home/vagrant/VRE-master/.pyvenv/lib64/python27.zip',
 '/home/vagrant/VRE-master/.pyvenv/lib64/python2.7',
 '/home/vagrant/VRE-master/.pyvenv/lib64/python2.7/plat-linux2',
 '/home/vagrant/VRE-master/.pyvenv/lib64/python2.7/lib-tk',
 '/home/vagrant/VRE-master/.pyvenv/lib64/python2.7/lib-old',
 '/home/vagrant/VRE-master/.pyvenv/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7',
 '/usr/lib/python2.7',
 '/home/vagrant/VRE-master/.pyvenv/lib/python2.7/site-packages',
 '/home/vagrant/VRE-master']

Server time:    Wed, 12 Oct 2016 15:02:29 +0000

**Comment by TomasKulhanek** [comment]
is the SP at 10.81.73.65:8004/saml2 some proprietar service or can it be added to source codes and deployed into the VM in order to manage this issue.

**Comment by Benzene** [comment]
I have updated the configuration so that it doesn't try to use SAML integration in local mode. Sorry, that shouldn't have been enabled at all. It is now back to using a local account database.

To integrate with ARIA, there is a private key necessary, that can't be shared between system (so I'm not publishing it on github). I'm not really sure how we can have SSO integration in the virtual folder box. We'll have to speak with the people handling the SSO to figure that out.

**Comment by TomasKulhanek** [comment]
Added django command to create vagrant user in single deployment scenario: manage.py createvagrant
